name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - "*"

jobs:
  code-quality:
    uses: ./.github/workflows/code-quality.yaml

  deploy:
    uses: ./.github/workflows/deploy.yaml
    secrets: inherit

